title: Default
template:

columns:
  # left/up
  left:
    width: 1/2
    sections:

      content:
        type: fields
        fields:

          # description (standard)
          text:
            label: Text
            type: textarea
            required: true
# -------------------------

  # right/down
  right:
    width: 1/2
    sections:

      # images (optional)
      cover:
        headline: Cover image
        type: files
        multiple: false

      # subpages (optional)
      pages:
        type: pages
        help: (optional)

# -------------------------
