title: Default
template:

columns:
  # left/up
  left:
    width: 1/2
    sections:

      content:
        type: fields
        fields:

          # description (standard)
          text:
            label: Text
            type: textarea
            required: true
          
          colophon:
            label: Colophon
            type: structure
            fields:
              role:
                label: Role
                type: text
              person:
                label: Person
                help: Select profiles from the people page
                type: pages
                multiple: true
                query: site.find('community').find('people')
              other:
                label: Other
                type: textarea
                help: Add people without a profile
# -------------------------

  # right/down
  right:
    width: 1/2
    sections:

      cover:
        headline: Cover image
        type: files
        max: 1
        template: cover
        label: Cover

      meta:
        type: fields
        fields:
          subpagesTitle:
            type: text
            label: Section title (subpages)
      pages:
        type: pages
        label: Subpages
        help: (optional)

      gallery:
        headline: Gallery
        type: files
        template: gallery
        label: Gallery

# -------------------------
